<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_GET</name>
   <tag></tag>
   <elementGuidId>5c000edc-1ae8-4790-894a-a0e2a63dc0fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='operations-pet-findPetsByStatus']/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.opblock-summary.opblock-summary-get > button.opblock-summary-control > span.opblock-summary-method</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8fe8ffe9-8fe2-4414-85bf-39f14cc65182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opblock-summary-method</value>
      <webElementGuid>9b3ebd6c-d924-43c7-9f5d-fc6b6c974a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GET</value>
      <webElementGuid>eece8725-aa77-41df-9d36-8e725752d923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operations-pet-findPetsByStatus&quot;)/div[@class=&quot;opblock-summary opblock-summary-get&quot;]/button[@class=&quot;opblock-summary-control&quot;]/span[@class=&quot;opblock-summary-method&quot;]</value>
      <webElementGuid>cd3ad3fd-ef0f-4821-985e-1e0d947b61ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='operations-pet-findPetsByStatus']/div/button/span</value>
      <webElementGuid>49165cbf-b8e1-4efe-aad2-b1ab023e532d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/div/div/button/span</value>
      <webElementGuid>d44a9b34-342a-4d53-b21c-35445e478fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'GET' or . = 'GET')]</value>
      <webElementGuid>f0d88451-f397-48d5-8cef-0b15349185ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
