<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_ecbiz312.inmotionhosting.com</name>
   <tag></tag>
   <elementGuidId>1a11b24e-cbd2-4fee-b8eb-92b8d8bdd3a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>06e917bc-0d8f-4562-b8d9-b76023245456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ecbiz312.inmotionhosting.com</value>
      <webElementGuid>4ba1787d-d14e-4834-9a9e-e7f8ce4751e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/font[1]/font[1]/strong[1]/h2[1]</value>
      <webElementGuid>88487823-1a02-4bc3-b2c6-9bd594dc60da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>93f835f2-9ea4-43e7-8568-5824e7f5653f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'ecbiz312.inmotionhosting.com' or . = 'ecbiz312.inmotionhosting.com')]</value>
      <webElementGuid>dbb895a8-f5e4-47fc-9757-f949517544a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
